# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'JSCoreBom', '~> 1.1.1'


target 'reduxTest' do

end

target 'reduxTestTests' do

end

target 'reduxTestUITests' do

end
